builds:
- binary: bump
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapcrafts:
  - summary: Command-line to bump version in a git repository
    description: |
      With bump you can bump version following semver.
      - bump major
      - bump minor
      - bump patch

      You can use it with or without "v" prefix.
    grade: stable
    publish: true
    license: Apache-2.0
    base: core18
    confinement: strict
    apps:
      bump:
        plugs: ["home", "personal-files"]
    plugs:
      personal-files:
        read:
        - $HOME/.gitconfig
brews:
  - tap:
      owner: guilhem
      name: homebrew-tap
      token: "{{ .Env.TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@barpilot.io
    homepage: "https://github.com/guilhem/bump"
    description: "Command-line to bump version in a git repository."
release:
