name: lint
on: [pull_request,push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run GolangCI-Lint Action by pulling pre-built image
      uses: matoous/golangci-lint-action@v1
      env:
        GO111MODULE: on
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
