name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Goreleaser
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: Checkout
        uses: actions/checkout@v1

      # snapcraft export-login --snaps bump -
      - name: Snapcraft Action
        uses: samuelmeuli/action-snapcraft@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
