name: release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Snapcraft Action
        uses: samuelmeuli/action-snapcraft@v1.2.0
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO111MODULE: on

